doit_flask/pybo/views/answer_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template, g
from werkzeug.utils import redirect
from pybo import db
from ..forms import AnswerForm
from pybo.models import Question, Answer
from pybo.views.auth_views import login_required
bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content,
                        create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('question/question_detail.html', question=question, form=form)

doit_flask/pybo/views/question_view.py
from flask import Blueprint, render_template
from pybo.models import Question

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    question_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question)

doit_flask/pybo/views/question_views.py
from datetime import datetime
from flask import Blueprint, render_template, request, url_for, g
from werkzeug.utils import redirect
from .. import db
from pybo.models import Question
from ..forms import QuestionForm, AnswerForm
from pybo.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)


@bp.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data,
                            content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

doit_flask/pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ question.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.user.username }}</div>
                    <div>{{ question.create_date|datetime }}</div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }} 개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.user.username }}</div>
                    <div>{{ answer.create_date|datetime }}</div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="POST" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류 표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{', '.join(errors)}}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <textarea {% if not g.user %} disabled {% endif %} name="content" id="content" rows="10"
                class="form-control"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

doit_flask/pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        <!-- 오류 표시 Start -->
        {{ form.csrf_token }}
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>
                {{ form[field].label }}
            </strong> : {{', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류 표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or ''}}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

doit_flask/pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="text-center thead-dark">
                <th>번호</th>
                <th style="width: 50%;">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list.items %}
            <tr class="text-center">
                <td>
                    {{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}
                </td>
                <td class="text-left">
                    <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                    
                    {% if question.answer_set|length > 0 %}
                        <span class="text-danger small ml-2"> {{ question.answer_set|length }}</span>
                    {% endif %}
                        
                </td>
                <td>{{ question.user.username }} </td>
                <td>{{ question.create_date|datetime }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a href="?page={{ question_list.prev_num }}" class="page-link">이전</a>
        </li>
        {% else %}
        <li class="page-item disabld">
            <a href="#" class="page-link" tabindex="-1" , aria-disabled="true">이전</a>
        </li>
        {% endif %}

        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-num">
            <a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a href="#" class="page-link">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a href="#" class="page-link">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a href="?page={{ question_list.next_num }}" class="page-link">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a href="#" class="page-link" tabindex="-1" aria-disabled="true">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝-->
    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}